package com.shinowit.dao.mapper;

import com.shinowit.entity.SexType;
import com.shinowit.entity.SexTypeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SexTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int countByExample(SexTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int deleteByExample(SexTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int deleteByPrimaryKey(String sexCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int insert(SexType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int insertSelective(SexType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    List<SexType> selectByExample(SexTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    SexType selectByPrimaryKey(String sexCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByExampleSelective(@Param("record") SexType record, @Param("example") SexTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByExample(@Param("record") SexType record, @Param("example") SexTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByPrimaryKeySelective(SexType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_type
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByPrimaryKey(SexType record);

    List<SexType> selectPage(SexTypeCriteria example);

    String selectMaxPrimaryKeyValue();
}