package com.shinowit.dao.mapper;

import com.shinowit.entity.Stu;
import com.shinowit.entity.StuCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int countByExample(StuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int deleteByExample(StuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int deleteByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int insert(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int insertSelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    List<Stu> selectByExample(StuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    Stu selectByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByExampleSelective(@Param("record") Stu record, @Param("example") StuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByExample(@Param("record") Stu record, @Param("example") StuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByPrimaryKeySelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByPrimaryKey(Stu record);

    List<Stu> selectPage(StuCriteria example);

    Integer selectMaxPrimaryKeyValue();
}