package com.shinowit.dao.mapper;

import com.shinowit.entity.Tea;
import com.shinowit.entity.TeaCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int countByExample(TeaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int deleteByExample(TeaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int deleteByPrimaryKey(Integer teaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int insert(Tea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int insertSelective(Tea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    List<Tea> selectByExample(TeaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    Tea selectByPrimaryKey(Integer teaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByExampleSelective(@Param("record") Tea record, @Param("example") TeaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByExample(@Param("record") Tea record, @Param("example") TeaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByPrimaryKeySelective(Tea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tea
     *
     * @mbggenerated Tue Dec 23 16:11:09 CST 2014
     */
    int updateByPrimaryKey(Tea record);

    List<Tea> selectPage(TeaCriteria example);

    Integer selectMaxPrimaryKeyValue();
}